version: '3.9'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - '4000:4000'
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network
