version: '3.9'
services:
  app:
    build: .
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "npx sequelize db:migrate && npx sequelize db:seed:all && npm run dev"

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
