version: '3.9'

services:
  app:
    build:
      context: .
      target: production
    ports:
      - '4000:4000'
    env_file:
      - .env.production
    depends_on:
      - db
    networks:
      - app-network
