version: '3.8'
services:
  app:
    build:
      context: .
      target: development
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev
    restart: unless-stopped

  app-prod:
    build:
      context: .
      target: production
    ports:
      - '4000:4000'
    env_file:
      - .env.prod
    depends_on:
      - db
    environment:
      NODE_ENV: production
    command: ["sh", "/wait-for-it.sh", "db:5432", "--", "npm", "start"]
    restart: unless-stopped

  db:
    image: postgres:15
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
