version: '3.9'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - '4000:4000'
    env_file:
      - .env.production
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev
    restart: unless-stopped

  app-prod:
    build:
      context: .
      target: production
    ports:
      - '4000:4000'
    env_file:
      - .env.production
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    env_file:
      - .env.production
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
